routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('report','ReportController');

app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    //
    protected $fillable = [
        'nombre', 'fechaingreso', 'fechasalida', 'diferencia'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Report;
use Carbon\Carbon;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $report = Report::orderBy('id', 'desc')->paginate(12);
        return view('lista', compact('report'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $report = new Report();
        $report->nombre = $request->nombre;
        $report->fechaingreso = $request->fechaingreso;
        $report->fechasalida = $request->fechasalida;

        $start = Carbon::parse($request->fechaingreso);
        $end = Carbon::parse($request->fechasalida);
        $length = $start->diffInMinutes($end);
        //obtener de otra manera
        $report->diferencia = $length;

        if($report->save()){
            return back()->with('msj','Datos enviados correctamente');
        }else{
            return back()->with('msj','Error al enviar datos');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $report = Report::find($id);
        return view('reporte', compact('report'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $report = Report::find($id);
        $report->nombre = $request->nombre;
        $report->fechaingreso = $request->fechaingreso;
        $report->fechasalida = $request->fechasalida;

        $start = Carbon::parse($request->fechaingreso);
        $end = Carbon::parse($request->fechasalida);
        $length = $start->diffInMinutes($end);
        //obtener de otra manera
        $report->diferencia = $length;

        if($report->save()){
            return back();
        }else{
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Report::destroy($id);

        return back();
    }
}

resources/views/lista.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    </head>
    <body>
        <div class="">
            <div class="content">
                <div class="title m-b-md">
                    Lista de datos
                </div>
                
                @if(isset($report))
                    <table border="1">
                        <thead>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Diferencia en minutos</th>
                        </thead>
                        <tbody>
                    @foreach($report as $r)
                        <tr>
                            <td>{{$r->id}}</td>
                            <td>{{$r->nombre}}</td>
                            <td>{{$r->fechaingreso}}</td>
                            <td>{{$r->fechasalida}}</td>
                            <td>{{$r->diferencia}}</td>
                            <td><a href="/report/{{$r->id}}/edit">Editar</a></td>
                            <td>
                                    <form class="deleteform" action="{{route('report.destroy', $r->id)}}" method="POST">
                                    <input name="_method" type="hidden" value="DELETE">
                                  {{ csrf_field() }}
                                 <input type="submit" class="btn btn-danger btn-xs clbutton" value="Eliminar">
                      </form>

                      </td>
                        </tr>
                    @endforeach
                    </tbody>
                    </table>
                @endif
                
            </div>
        </div>
    </body>
</html>

resources/views/reporte.blade.php
<!doctype html>

<html lang="{{ app()->getLocale() }}">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
    </head>
    <body>

<div class="content">
                <div class="title m-b-md">
                    Formulario
                </div>
                @if(isset($report))
                <form action="{{route('report.update',$report->id)}}" method="POST" name="myform">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">
                        <input type="text" name="nombre" value="{{$report->nombre}}">
                        <input type="text" name="fechaingreso" value="{{$report->fechaingreso}}">
                        <input type="text" name="fechasalida" value="{{$report->fechasalida}}">

                        <button type="input">Modificar datos</button>
                </form>
                @endif
                
            </div>


</body>
</html>